<div id="pronoun-correlations">
	<h2>Pronoun Correlations</h2>
	<table id="pronouncorrelations">
		<thead>
			<tr>
				<th></th>
				<th>Query</th>
				<th>This</th>
				<th>That</th>
				<th>Some</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><strong>Adjective</strong></td>
				<td>which</td>
				<td>this</td>
				<td>that</td>
				<td>some</td>
			</tr>
			<tr>
				<td></td>
				<td>čekë</td>
				<td>četet</td>
				<td>tet</td>
				<td>monet</td>
			</tr>
			<tr>
				<td><strong>Person</strong></td>
				<td>who</td>
				<td>this</td>
				<td>that</td>
				<td>someone</td>
			</tr>
			<tr>
				<td></td>
				<td>ko</td>
				<td>četet</td>
				<td>tot</td>
				<td>monkot</td>
			</tr>
			<tr>
				<td><strong>Thing</strong></td>
				<td>what</td>
				<td>this</td>
				<td>that</td>
				<td>something</td>
			</tr>
			<tr>
				<td></td>
				<td>kë</td>
				<td>četet</td>
				<td>tet</td>
				<td>montet</td>
			</tr>
			<tr>
				<td><strong>Place</strong></td>
				<td>where</td>
				<td>here</td>
				<td>there</td>
				<td>somewhere</td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><strong>Time</strong></td>
				<td>when</td>
				<td>now</td>
				<td>then</td>
				<td>sometime</td>
			</tr>
			<tr>
				<td></td>
				<td>kijal</td>
				<td>čekijat</td>
				<td>kijat</td>
				<td>monkijat</td>
			</tr>
			<tr>
				<td><strong>Way</strong></td>
				<td>how</td>
				<td></td>
				<td>thus</td>
				<td>somehow</td>
			</tr>
			<tr>
				<td></td>
				<td>ku</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><strong>Reason</strong></td>
				<td>why</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div>

<!-- <ul>
<li>Finno-Ugric descriptors</li>
<li>Romantic nouns</li>
<li>Germanic actions</li>
</ul> -->
